try {
    x();
} catch (ex) {
    print('caught\n');
}